name: 'fund-on-stackaid'
on:
  push:
    branches:
      - master
jobs:
  stackaid-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3 # Only required for Go based repos
      - uses: stackaid/generate-stackaid-json@v1.9
