on: [push, pull_request]
name: CI
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Init Hermit
        run: ./bin/hermit env --raw >> $GITHUB_ENV
      - name: Test
        run: go test ./...
      - name: Lint
        run: golangci-lint run
