version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      gha:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directories:
      - /
      - build
      - internal/e2e
      - wafbench
    schedule:
      interval: weekly
    groups:
      go:
        patterns:
          - "*"
